/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batch-notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batch_notes_list"];
        put?: never;
        post: operations["batch_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch-notes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batch_notes_retrieve"];
        put: operations["batch_notes_update"];
        post?: never;
        delete: operations["batch_notes_destroy"];
        options?: never;
        head?: never;
        patch: operations["batch_notes_partial_update"];
        trace?: never;
    };
    "/api/batches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batches_list"];
        put?: never;
        post: operations["batches_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batches_retrieve"];
        put: operations["batches_update"];
        post?: never;
        delete: operations["batches_destroy"];
        options?: never;
        head?: never;
        patch: operations["batches_partial_update"];
        trace?: never;
    };
    "/api/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ingredients_list"];
        put?: never;
        post: operations["ingredients_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ingredients_retrieve"];
        put: operations["ingredients_update"];
        post?: never;
        delete: operations["ingredients_destroy"];
        options?: never;
        head?: never;
        patch: operations["ingredients_partial_update"];
        trace?: never;
    };
    "/api/recipe-ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipe_ingredients_list"];
        put?: never;
        post: operations["recipe_ingredients_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe-ingredients/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipe_ingredients_retrieve"];
        put: operations["recipe_ingredients_update"];
        post?: never;
        delete: operations["recipe_ingredients_destroy"];
        options?: never;
        head?: never;
        patch: operations["recipe_ingredients_partial_update"];
        trace?: never;
    };
    "/api/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipes_list"];
        put?: never;
        post: operations["recipes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipes_retrieve"];
        put: operations["recipes_update"];
        post?: never;
        delete: operations["recipes_destroy"];
        options?: never;
        head?: never;
        patch: operations["recipes_partial_update"];
        trace?: never;
    };
    "/api/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Batch: {
            readonly id: number;
            recipe: number;
            /** Format: decimal */
            batch_size_g: string;
            /** Format: decimal */
            concentration?: string;
            maceration_days?: number;
            /** Format: date */
            made_on: string;
            status?: components["schemas"]["StatusEnum"];
            rating?: number | null;
            /** Format: date-time */
            readonly created_at: string;
            readonly aromatic_g: string;
            readonly diluent_g: string;
            readonly recipe_was_balanced: boolean;
            readonly days_macerating: number;
            /** Format: date */
            readonly ready_on: string;
            readonly days_remaining: number;
            readonly maceration_progress: string;
            readonly is_due: boolean;
            readonly ingredients: components["schemas"]["BatchIngredient"][];
            readonly notes: components["schemas"]["BatchNote"][];
        };
        BatchIngredient: {
            readonly id: number;
            readonly ingredient: number;
            readonly ingredient_name: string;
            /** Format: decimal */
            readonly proportion: string;
            /** Format: decimal */
            readonly grams: string;
        };
        BatchNote: {
            readonly id: number;
            batch: number;
            /** Format: date */
            observed_on: string;
            body: string;
            readonly day_number: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        Ingredient: {
            readonly id: number;
            name: string;
            article_number?: string | null;
            supplier?: string | null;
            description?: string | null;
            /** Format: decimal */
            dilution_strength?: string;
            /** Format: decimal */
            density_g_per_ml?: string | null;
            notes?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        PaginatedBatchList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Batch"][];
        };
        PaginatedBatchNoteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BatchNote"][];
        };
        PaginatedIngredientList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Ingredient"][];
        };
        PaginatedRecipeIngredientList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RecipeIngredient"][];
        };
        PaginatedRecipeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Recipe"][];
        };
        PatchedBatch: {
            readonly id?: number;
            recipe?: number;
            /** Format: decimal */
            batch_size_g?: string;
            /** Format: decimal */
            concentration?: string;
            maceration_days?: number;
            /** Format: date */
            made_on?: string;
            status?: components["schemas"]["StatusEnum"];
            rating?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
            readonly aromatic_g?: string;
            readonly diluent_g?: string;
            readonly recipe_was_balanced?: boolean;
            readonly days_macerating?: number;
            /** Format: date */
            readonly ready_on?: string;
            readonly days_remaining?: number;
            readonly maceration_progress?: string;
            readonly is_due?: boolean;
            readonly ingredients?: components["schemas"]["BatchIngredient"][];
            readonly notes?: components["schemas"]["BatchNote"][];
        };
        PatchedBatchNote: {
            readonly id?: number;
            batch?: number;
            /** Format: date */
            observed_on?: string;
            body?: string;
            readonly day_number?: number;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedIngredient: {
            readonly id?: number;
            name?: string;
            article_number?: string | null;
            supplier?: string | null;
            description?: string | null;
            /** Format: decimal */
            dilution_strength?: string;
            /** Format: decimal */
            density_g_per_ml?: string | null;
            notes?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedRecipe: {
            readonly id?: number;
            name?: string;
            description?: string | null;
            /** Format: decimal */
            default_concentration?: string;
            diluent_name?: string;
            default_maceration_days?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly recipe_ingredients?: components["schemas"]["RecipeIngredient"][];
            readonly proportions_total?: string;
            readonly is_balanced?: boolean;
        };
        PatchedRecipeIngredient: {
            readonly id?: number;
            recipe?: number;
            ingredient?: number;
            readonly ingredient_name?: string;
            /** Format: decimal */
            proportion?: string;
        };
        Recipe: {
            readonly id: number;
            name: string;
            description?: string | null;
            /** Format: decimal */
            default_concentration: string;
            diluent_name?: string;
            default_maceration_days?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly recipe_ingredients: components["schemas"]["RecipeIngredient"][];
            readonly proportions_total: string;
            readonly is_balanced: boolean;
        };
        RecipeIngredient: {
            readonly id: number;
            recipe: number;
            ingredient: number;
            readonly ingredient_name: string;
            /** Format: decimal */
            proportion: string;
        };
        Register: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            password: string;
        };
        /**
         * @description * `macerating` - Macerating
         *     * `ready` - Ready
         *     * `archived` - Archived
         * @enum {string}
         */
        StatusEnum: "macerating" | "ready" | "archived";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    batch_notes_list: {
        parameters: {
            query?: {
                batch?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBatchNoteList"];
                };
            };
        };
    };
    batch_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchNote"];
                "application/x-www-form-urlencoded": components["schemas"]["BatchNote"];
                "multipart/form-data": components["schemas"]["BatchNote"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchNote"];
                };
            };
        };
    };
    batch_notes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchNote"];
                };
            };
        };
    };
    batch_notes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchNote"];
                "application/x-www-form-urlencoded": components["schemas"]["BatchNote"];
                "multipart/form-data": components["schemas"]["BatchNote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchNote"];
                };
            };
        };
    };
    batch_notes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batch_notes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBatchNote"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBatchNote"];
                "multipart/form-data": components["schemas"]["PatchedBatchNote"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchNote"];
                };
            };
        };
    };
    batches_list: {
        parameters: {
            query?: {
                is_due?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
                recipe?: number;
                /**
                 * @description * `macerating` - Macerating
                 *     * `ready` - Ready
                 *     * `archived` - Archived
                 */
                status?: "archived" | "macerating" | "ready";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBatchList"];
                };
            };
        };
    };
    batches_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Batch"];
                "application/x-www-form-urlencoded": components["schemas"]["Batch"];
                "multipart/form-data": components["schemas"]["Batch"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    batches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    batches_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Batch"];
                "application/x-www-form-urlencoded": components["schemas"]["Batch"];
                "multipart/form-data": components["schemas"]["Batch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    batches_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batches_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBatch"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBatch"];
                "multipart/form-data": components["schemas"]["PatchedBatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    ingredients_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngredientList"];
                };
            };
        };
    };
    ingredients_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"];
                "application/x-www-form-urlencoded": components["schemas"]["Ingredient"];
                "multipart/form-data": components["schemas"]["Ingredient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    ingredients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    ingredients_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingredient"];
                "application/x-www-form-urlencoded": components["schemas"]["Ingredient"];
                "multipart/form-data": components["schemas"]["Ingredient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    ingredients_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingredients_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIngredient"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIngredient"];
                "multipart/form-data": components["schemas"]["PatchedIngredient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    recipe_ingredients_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                recipe?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipeIngredientList"];
                };
            };
        };
    };
    recipe_ingredients_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeIngredient"];
                "application/x-www-form-urlencoded": components["schemas"]["RecipeIngredient"];
                "multipart/form-data": components["schemas"]["RecipeIngredient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeIngredient"];
                };
            };
        };
    };
    recipe_ingredients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeIngredient"];
                };
            };
        };
    };
    recipe_ingredients_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeIngredient"];
                "application/x-www-form-urlencoded": components["schemas"]["RecipeIngredient"];
                "multipart/form-data": components["schemas"]["RecipeIngredient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeIngredient"];
                };
            };
        };
    };
    recipe_ingredients_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recipe_ingredients_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe ingredient. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecipeIngredient"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecipeIngredient"];
                "multipart/form-data": components["schemas"]["PatchedRecipeIngredient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeIngredient"];
                };
            };
        };
    };
    recipes_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipeList"];
                };
            };
        };
    };
    recipes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
                "application/x-www-form-urlencoded": components["schemas"]["Recipe"];
                "multipart/form-data": components["schemas"]["Recipe"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
        };
    };
    recipes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
        };
    };
    recipes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recipe"];
                "application/x-www-form-urlencoded": components["schemas"]["Recipe"];
                "multipart/form-data": components["schemas"]["Recipe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
        };
    };
    recipes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recipes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this recipe. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecipe"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecipe"];
                "multipart/form-data": components["schemas"]["PatchedRecipe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
        };
    };
    register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
}
